name: Run UI Tests with Chrome Driver

on:
  workflow_dispatch:
  push:
    paths:
      - '.env'


jobs:
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run UI Tests
        env:
          APITEST_PASSWORD: ${{ secrets.APITEST_PASSWORD }}
        run: docker compose up --build --abort-on-container-exit
